### ISSUE TITLE
SASS color math

### ISSUE THREAD

**Issue by M374LX** [cleydyr/biblivre#243]
Newer SASS versions have removed color math, as seen in https://github.com/sass/sass/issues/2144.

Here are the lines that still use color math:
https://github.com/cleydyr/biblivre/blob/5646e38e9f87b1baef978e6ea8610c2cc3378ede/WebContent/static/styles/scss/_biblivre.scss#L18
https://github.com/cleydyr/biblivre/blob/5646e38e9f87b1baef978e6ea8610c2cc3378ede/WebContent/static/styles/scss/_mixins.scss#L38
https://github.com/cleydyr/biblivre/blob/5646e38e9f87b1baef978e6ea8610c2cc3378ede/WebContent/static/styles/scss/interface/_menu.scss#L2.

**Comment by cleydyr** [comment]
Hi, @M374LX .

Thank you for submitting this PR. I really appreciate the effort you put into contributing to this repo.

Currently I have plans to revamp the frontend entirely to make it more accessible, maintainable, responsive and (if luckily) faster. That will likely wipe all the current theming. I don't see it coming in the short term, though.

I believe that upgrading the current plugin will make the current Sass processing more robust. However, in that same line or reasoning, I wonder if we could upgrade the Sass processing directly to [Libsass Maven Plugin](https://gitlab.com/haynes/libsass-maven-plugin) as [Ruby Sass has been discontinued](https://sass-lang.com/blog/ruby-sass-is-unsupported).

A new PR with that change to Libsass would be awesome.

Cheers!
