### ISSUE TITLE
Reindexação e Backup / Catalogação

### ISSUE THREAD

**Issue by mateus-marchi** [cleydyr/biblivre#323]
Bom dia Cleydyr.

Em relação ao problema na reindexação e backup realizados pelo software Biblivre, seguem logs para você olhar, assim fica mais fácil de identificar um possível problema.

[localhost.2022-03-09.log](https://github.com/cleydyr/biblivre/files/8215108/localhost.2022-03-09.log)
[biblivre-logger.log](https://github.com/cleydyr/biblivre/files/8215109/biblivre-logger.log)

Nesses logs enviados, tentei executar a reindexação, o backup completo e backup sem mídia digital também, todos sem sucesso, sendo que na reindexação retorna "Erro inesperado durante a execução da tarefa" e nos backups o status apresentado em rela não sai do zero.

Meu servidor está configurado para funcionar com HTTS/SSL, não sei se teria tratamento diferente no software por requisições via porta 80 e 443.

Também observei que na função Administração / Configuração, área de "Dias de Funcionamento" os caracteres que possuem acentos estão todos desconfigurados com relação a codificação de acentuação.

Muito obrigado, estou a disposição.

**Comment by cleydyr** [comment]
Oi, @mateus-marchi .

Obrigado pelo relato detalhado dos bugs que estão afetando a versão master.

> Nesses logs enviados, tentei executar a reindexação, o backup completo e backup sem mídia digital também, todos sem sucesso, sendo que na reindexação retorna "Erro inesperado durante a execução da tarefa" e nos backups o status apresentado em rela não sai do zero.

Sobre a reindexação, isso está acontecendo porque o registro está retornando null como número de controle. Provavelmente seu registro não tem o campo MARC 001 definido. Você pode compartilhar comigo a fonte dos seus registros (um backup ou um arquivo iso2701, por exemplo) para eu tentar reproduzir o problema?


> Meu servidor está configurado para funcionar com HTTS/SSL, não sei se teria tratamento diferente no software por requisições via porta 80 e 443.

Não faz diferença a porta que você usa para enviar a requisição. O Biblivre está estruturado para abstrair essa parte dos detalhes de rede.


> Também observei que na função Administração / Configuração, área de "Dias de Funcionamento" os caracteres que possuem acentos estão todos desconfigurados com relação a codificação de acentuação.

Não consigo ver esse comportamento sendo reproduzido quando uso o Docker Compose de acordo com as instruções. Você implantou direto no Windows?


> Também encontramos a mensagem de "Erro inesperado durante a execução da tarefa" em uma rotina importante.
> 
> O erro ocorre na função "Catalogação - Bibliográfica - Novo Registro", ao clicar entre as abas "Resumo - MARC - Exemplares" a mensagem é exibida e o software não muda para a aba selecionada.

Eu consegui reproduzir esse erro e vou investigar.

**Comment by cleydyr** [comment]
P.S.: Eu fiz algumas mudanças no branch issue-323. Se você puder verificar se os erros ainda persistem seria ótimo.

**Comment by mateus-marchi** [comment]
Bom dia @cleydyr .

Eu que agradeço pelos retornos, obrigado.

>  Obrigado pelo relato detalhado dos bugs que estão afetando a versão master.

Certo, entendi. Te encaminhei o arquivo de backup do banco de dados para que possa tentar simular o problema.
A princípio existe alguma instrução SQL que eu possa executar para preencher os registros MARC 001 que estão nulos?

> Sobre a reindexação, isso está acontecendo porque o registro está retornando null como número de controle. Provavelmente seu registro não tem o campo MARC 001 definido. Você pode compartilhar comigo a fonte dos seus registros (um backup ou um arquivo iso2701, por exemplo) para eu tentar reproduzir o problema?

Sim, implantei diretamente no Windows.

> Não consigo ver esse comportamento sendo reproduzido quando uso o Docker Compose de acordo com as instruções. Você implantou direto no Windows?

Os erros na abertura das telas "Resumo - MARC - Exemplares" não acontecem mais, agora estão abrindo conforme o necessário.

> P.S.: Eu fiz algumas mudanças no branch issue-323. Se você puder verificar se os erros ainda persistem seria ótimo.

Muito obrigado, estou a disposição.

**Comment by cleydyr** [comment]
Oi, @mateus-marchi .

Na sua biblioteca CEU das artes existem 49 registros sem o campo 001 definido. Eu creio que a versão oficial do Biblivre é mais liberal nesse sentido e permite que o identificador da base de dados e o campo 001 do marc não sejam iguais (ou que o campo 001 sequer exista). Nessa versão master eu usei o marc como fonte da verdade.

Eu adicionei um commit no branch issue-323. Pode dar uma checada e confirmar que agora a indexação está funcionando?

**Comment by mateus-marchi** [comment]
Olá, @cleydyr .

Testei a função de Reindexação da Base de Dados (CEU) e a mesma funcionou perfeitamente, retornando "Reindexação concluída com sucesso".

> Eu adicionei um commit no branch issue-323. Pode dar uma checada e confirmar que agora a indexação está funcionando?

Muito obrigado! 

Estou a disposição.
