### ISSUE TITLE
Não está gravando modificação em Personalização de Formulário Catalográfico

### ISSUE THREAD

**Issue by Alex-Almeida** [cleydyr/biblivre#330]
Boa noite

Instalei o programa seguindo as instruções para o Docker Compose (master) para fazer uma modificação bem específica (ao imprimir etiqueta não gerar o código de barras) e notei duas situações:

**Problema 1**
Não está salvando as modificações feitas em Personalização de Formulário Catalográfico.
Como reproduzir:
- Acessar "Administração" -> "Personalização de Formulário Catalográfico"
- Expandir qualquer campo (ex: ISBN)
- Alterar o "Nome do Subcampo" para qualquer coisa
- Salvar a modificação
- Mudar para outra pagina (ex: "Catalogação ->Bibliográfica)
- Voltar para "Personalização de Formulário Catalográfico"
- Expandir o campo editado e verificar que não salvou

**Problema 2**
Ao adicionar um novo subcampo não salva o nome digitado e o "Nome do subcampo" vira __marc.bibliographic.datafield.020.subfield.X__ (X seria a letra usada no MARC)
Como reproduzir:
- Acessar "Administração" -> "Personalização de Formulário Catalográfico"
- Expandir qualquer campo (ex: ISBN)
- Clicar no "+" no fim de "Subcampos"
- Digitar uma letra em "MARC" (ex: b)
- Digitar qualquer coisa em "Nome do Subcampo"
- Salvar a modificação
- Mudar para outra pagina (ex: "Catalogação ->Bibliográfica)
- Voltar para "Personalização de Formulário Catalográfico"
- Expandir o campo editado e verificar que alterou o "Nome do Subcampo" para __marc.bibliographic.datafield.020.subfield.b__

Aproveitando, queria tentar usar a versão debug no código para entender melhor como algumas coisas funcionam (esses erros por exemplo). Mas estou usando o comando "mvn clean package -P developer -DskipTests" e diz que está executando os testes mesmo com o -DskipTests. E a execução dos testes está dando vários erros, não executando o programa com esse comando.
Tem que fazer alguma coisa a mais pra isso? 
Tbm é a primeira vez q utilizou Docker, como funcionaria isso: "The developer profile will activate the debug flag to allow you to debug Biblivre remotely"?

**Comment by cleydyr** [comment]
A propósito, sobre a flag skipTests, realmente não está funcionando para o perfil `developer`, então eu vou ter que modificar o README para a documentação ficar consistente. Enquanto isso você pode usar `-Dmaven.test.skip=true` em vez de `-DskipTests` para pular os testes. A razão de os testes, quando são executados, estarem falhando pode ser porque o Docker não está sendo executado na sua máquina (os testes dependem de o Docker estar instalado e executando).

**Comment by Alex-Almeida** [comment]
> Oi, @Alex-Almeida .
> 
> Obrigado pelo detalhamento dos problemas que você encontrou. Isso ajuda muito a fazer a triagem.
> 
> Eu consegui reproduzir o problema, já identifiquei a origem e consertei ele no branch issue-330, se quiser já usá-lo. Vou tentar adicionar uns testes e enviar um pull request em breve.

Mto obrigado, baixei o branch issue-330 e está funcionando.

> A propósito, sobre a flag skipTests, realmente não está funcionando para o perfil `developer`, então eu vou ter que modificar o README para a documentação ficar consistente. Enquanto isso você pode usar `-Dmaven.test.skip=true` em vez de `-DskipTests` para pular os testes. A razão de os testes, quando são executados, estarem falhando pode ser porque o Docker não está sendo executado na sua máquina (os testes dependem de o Docker estar instalado e executando).

Esse novo comando funcionou tbm, agora está pulando os testes.

**Comment by Alex-Almeida** [comment]
Boa noite @cleydyr 
Eu vi que na master essa correção não está funcionando. Analisando o código modificado aqui e o da master, teve uma alteração feita aqui que não foi pra lá (não sei se intencional ou alguma complicação do merge)
No arquivo _src/main/java/biblivre/core/translations/Translations.java_ ainda está fazendo 
```
return SchemaThreadLocal.withSchema(
                            Constants.GLOBAL_SCHEMA,
```
Enquanto que na correção aqui tu alterou para:
```
return SchemaThreadLocal.withSchema(
        		schema,
```

**Comment by cleydyr** [comment]
Verdade. Em algum merge a alteração foi desfeita. Eu vou refazer a correção no master e atualizar.
